version: '3.8'
services:
  # zookeeper:
  #   container_name: zookeeper
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - 2181:2181
  # kafka:
  #   container_name: kafka
  #   image: wurstmeister/kafka
  #   ports:
  #     - 9092:9092
  #   volumes:
  #     - ./data/kafka:/var/run/docker.sock
  #   environment: 
  #     - KAFKA_ADVERTISED_HOST_NAME = kafka
  #     - KAFKA_ZOOKEEPER_CONNECT = zookeeper:2181
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  server_app_one:
    container_name: server_app_one
    image: server_app_one
    build: ./server_app_one
    ports:
      - 8080:8080
    volumes:
      - ./server_app_one:/app
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - postgres
      - kafka
  server_app_two:
    container_name: server_app_two
    image: server_app_two
    build: ./server_app_two
    ports:
      - 8081:8080
    volumes:
      - ./server_app_two:/app
    environment:
      - PORT=8081
      - MONGO_URL=mongodb://mongo:27017/server_app_two
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - postgres
      - kafka
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local


